
// Mapping of Preeti font characters to Unicode Nepali characters
const preetiToUnicodeMap: Record<string, string> = {
  // Basic vowels and consonants
  'c': 'अ',
  'cf': 'आ',
  'O': 'इ',
  'O{': 'ई',
  'p': 'उ',
  'pm': 'ऊ',
  'C': 'ए',
  'P]': 'ऐ',
  'cf]': 'ओ',
  'cf}': 'औ',
  's': 'क',
  'v': 'ख',
  'u': 'ग',
  '3': 'घ',
  'ª': 'ङ',
  'r': 'च',
  '5': 'छ',
  'h': 'ज',
  'em': 'झ',
  '`': 'ञ',
  '6': 'ट',
  '7': 'ठ',
  '8': 'ड',
  '9': 'ढ',
  '0f': 'ण',
  't': 'त',
  'y': 'थ',
  'b': 'द',
  'w': 'ध',
  'g': 'न',
  'k': 'प',
  'km': 'फ',
  'a': 'ब',
  'e': 'भ',
  'd': 'म',
  'o': 'य',
  '/': 'र',
  'n': 'ल',
  'j': 'व',
  'z': 'श',
  'if': 'ष',
  ';': 'स',
  'x': 'ह',
  'If': 'क्ष',
  'q': 'त्र',
  '1': 'ज्ञ',
  
  // Maatras and other modifiers
  'f': 'ा',
  'l': 'ि',
  'L': 'ी',
  '\'': 'ु',
  '\"': 'ू',
  ']': 'े',
  '}': 'ै',
  'f]': 'ो',
  'f}': 'ौ',
  '\\': '्',
  '+': 'ं',
  // Removed duplicate % character
  'M': 'ः',
  
  // Common combinations
  'g]': 'ने',
  'kf': 'पा',
  'Gb': 'न्द',
  'b]': 'दे',
  'xf]': 'हो',
  '\\.': '।',
  'lxdf': 'हिमा',
  'kxf': 'पहा',
  't/f': 'तरा',
  'efiff': 'भाषा',
  'xfd|f]': 'हाम्रो',
  '/fi': 'राष्',
  '6«': 'ट्र',
  'af]': 'बो',
  'Ng': 'ल्न',
  'n]': 'ले',
  'Vg': 'ख्न',
  'hfGg': 'जान्न',
  'sf]': 'को',
  'cfh': 'आज',
  'w]/}': 'धेरै',
  '/fd|f]': 'राम्रो',
  'cfsfz': 'आकाश',
  ';kmf': 'सफा',
  '\"o{': 'ूर्य',
  'rDsL': 'चम्की',
  '/x]': 'रहे',
  ';+:s[lt': 'संस्कृति',
  'k/Dk/f': 'परम्परा',
  'clt': 'अति',
  ';d[4': 'समृद्ध',
  ';+/If': 'संरक्ष',
  'd]/f]': 'मेरो',
  'gfd': 'नाम',
  's[i0f': 'कृष्ण',
  'a:': 'बस्',
  'dnfO{': 'मलाई',
  'vfgf': 'खाना',
  'dg': 'मन',
  'k5{': 'पर्छ',
  'sIff': 'कक्षा',
  'df': 'मा',
  'gofF': 'नयाँ',
  'lzIfs': 'शिक्षक',
  'cfpg': 'आउन',
  'eof]': 'भयो',
  'pxfF': 'उहाँ',
  ';w}+': 'सधैं',
  'uLtf': 'गीता',
  'Ps': 'एक',
  'd]xg': 'मेहन',
  '5fqf': 'छात्रा',
  'cÍ': 'अंक',
  'ofpF': 'याउँ',
  ';a}': 'सबै',
  'dfof': 'माया',
  'u5{': 'गर्छ',
  'g\\\\': 'न्',
  'k9\\\\g': 'पढ्न',
  '1fg': 'ज्ञान',
  ';|f]t': 'स्रोत',
  'zlQm': 'शक्ति',
  'afgL': 'बानी',
  'a;fNg': 'बसाल्न',
  '/fd': 'राम',
  'Zofd': 'श्याम',
  'b\'O{': 'दुई',
  ';fyL': 'साथी',
  'x\'': 'हु',
  ';Fu}': 'सँगै',
  'v]N': 'खेल्',
  'rf8': 'चाड',
  'kj{': 'पर्व',
  'dxTj': 'महत्व',
  'b;}+': 'दशैं',
  'ltxf/': 'तिहार',
  '57': 'छठ',
  'cGo': 'अन्य',
  'v\'z': 'खुश',
  'Ln]': 'ीले',
  'dgf': 'मना',
  'OG5': 'इन्छ',
  
  // Numerals
  '!=': '१',
  '@=': '२', 
  '#=': '३',
  '$=': '४',
  '%=': '५', // Changed % to %= to avoid duplicate
  '^=': '६',
  '&=': '७',
  '*=': '८',
  '(=': '९',
  ')=': '०',
};

// Function to convert Preeti text to Unicode
export const preetiToUnicode = (preetiText: string): string => {
  // This is a simplified conversion - a full conversion would require more extensive mapping
  // and processing of complex character combinations
  let unicodeText = preetiText;
  
  // Replace multi-character combinations first (longer patterns before shorter ones)
  Object.keys(preetiToUnicodeMap)
    .sort((a, b) => b.length - a.length)
    .forEach(key => {
      unicodeText = unicodeText.split(key).join(preetiToUnicodeMap[key]);
    });
    
  return unicodeText;
};
